#!/usr/bin/env python3
"""
Certificate Generation Script for ZTA Government System - BANGLADESH VERSION
Generates only Root CA and Server certificates (no test users)
User certificates will be generated during manual registration
"""

import os
import subprocess
import json
from datetime import datetime, timedelta

# ========== CONFIGURATION ==========
OPENSSL_PATH = r"C:\Program Files\OpenSSL-Win64\bin\openssl.exe"
CERT_DIR = "./certs"
# ===================================


def run_openssl(args):
    """Execute OpenSSL command with full path"""
    cmd = [OPENSSL_PATH] + args
    cmd_str = " ".join(cmd)
    print(f"  Running: {cmd_str[:80]}...")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"  Error: {result.stderr[:200]}")
            return False
        return True
    except Exception as e:
        print(f"  Exception: {e}")
        return False


def generate_certificates():
    """Generate only Root CA and Server certificates"""
    print("=" * 60)
    print("🇧🇩 ZTA Government System - Bangladesh Certificate Generation 🇧🇩")
    print("=" * 60)

    # Verify OpenSSL exists
    if not os.path.exists(OPENSSL_PATH):
        print(f"\n❌ ERROR: OpenSSL not found at: {OPENSSL_PATH}")
        print("Please update OPENSSL_PATH in this script")
        return False

    print(f"✓ Using OpenSSL at: {OPENSSL_PATH}")
    os.makedirs(CERT_DIR, exist_ok=True)

    # 1. Generate Root CA - BANGLADESH GOVERNMENT
    print("\n1. Generating Root Certificate Authority (Bangladesh)...")

    # Generate CA key
    if not run_openssl(["genrsa", "-out", f"{CERT_DIR}/ca.key", "4096"]):
        print("Failed to generate CA key")
        return False

    # Generate CA certificate with BANGLADESH context
    ca_args = [
        "req",
        "-x509",
        "-new",
        "-nodes",
        "-key",
        f"{CERT_DIR}/ca.key",
        "-sha256",
        "-days",
        "3650",
        "-out",
        f"{CERT_DIR}/ca.crt",
        "-subj",
        "/C=BD/ST=Dhaka Division/L=Dhaka/O=Government of Bangladesh/OU=ZTA Project/CN=Government ZTA Root CA",
    ]

    if not run_openssl(ca_args):
        print("Failed to generate CA certificate")
        return False

    print("✅ Bangladesh Root CA created")

    # 2. Generate Server Certificate - BANGLADESH GOVERNMENT SERVER
    print("\n2. Generating Server Certificate (Bangladesh Government)...")

    # Generate server key
    if not run_openssl(["genrsa", "-out", f"{CERT_DIR}/server.key", "2048"]):
        return False

    # Create CSR with BANGLADESH context
    csr_args = [
        "req",
        "-new",
        "-key",
        f"{CERT_DIR}/server.key",
        "-out",
        f"{CERT_DIR}/server.csr",
        "-subj",
        "/C=BD/ST=Dhaka Division/L=Dhaka/O=Government ICT/OU=Digital Services/CN=zta.gov.bd",
    ]
    if not run_openssl(csr_args):
        return False

    # Create extensions file
    ext_content = """authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = zta.gov.bd
IP.1 = 127.0.0.1
"""

    with open(f"{CERT_DIR}/server.ext", "w") as f:
        f.write(ext_content)

    # Sign certificate
    sign_args = [
        "x509",
        "-req",
        "-in",
        f"{CERT_DIR}/server.csr",
        "-CA",
        f"{CERT_DIR}/ca.crt",
        "-CAkey",
        f"{CERT_DIR}/ca.key",
        "-CAcreateserial",
        "-out",
        f"{CERT_DIR}/server.crt",
        "-days",
        "365",
        "-sha256",
        "-extfile",
        f"{CERT_DIR}/server.ext",
    ]

    if not run_openssl(sign_args):
        return False

    print("✅ Bangladesh Server certificate created")

    # 3. Create OPA Agent keys directory (empty - keys will be generated by OPA Agent)
    print("\n3. Creating directory structure...")

    # Create clients directory for future user certificates
    clients_dir = os.path.join(CERT_DIR, "clients")
    os.makedirs(clients_dir, exist_ok=True)
    print(f"   ✓ Created: {clients_dir}")

    # Create OPA Agent directory
    opa_agent_dir = os.path.join(CERT_DIR, "opa_agent")
    os.makedirs(opa_agent_dir, exist_ok=True)
    print(f"   ✓ Created: {opa_agent_dir}")

    # Create services directory for service certificates
    services_dir = os.path.join(CERT_DIR, "services")
    os.makedirs(services_dir, exist_ok=True)
    print(f"   ✓ Created: {services_dir}")

    # Create user_keys directory for RSA keys
    user_keys_dir = os.path.join(CERT_DIR, "user_keys")
    os.makedirs(user_keys_dir, exist_ok=True)
    print(f"   ✓ Created: {user_keys_dir}")

    # 4. Create verification file
    print("\n4. Creating verification metadata...")

    metadata = {
        "generated_at": datetime.now().isoformat(),
        "country": "Bangladesh",
        "organization": "Government of Bangladesh",
        "certificate_authority": {
            "path": f"{CERT_DIR}/ca.crt",
            "subject": "/C=BD/ST=Dhaka Division/L=Dhaka/O=Government of Bangladesh/OU=ZTA Project/CN=Government ZTA Root CA",
            "validity_days": 3650,
        },
        "server_certificate": {
            "path": f"{CERT_DIR}/server.crt",
            "subject": "/C=BD/ST=Dhaka Division/L=Dhaka/O=Government ICT/OU=Digital Services/CN=zta.gov.bd",
            "validity_days": 365,
            "alt_names": ["localhost", "zta.gov.bd", "127.0.0.1"],
        },
        "directories_created": {
            "clients": clients_dir,
            "opa_agent": opa_agent_dir,
            "services": services_dir,
            "user_keys": user_keys_dir,
        },
        "notes": [
            "Root CA and Server certificates generated successfully",
            "User certificates will be generated during manual registration",
            "OPA Agent keys will be generated when OPA Agent starts",
            "Service certificates can be generated as needed",
        ],
    }

    with open(f"{CERT_DIR}/metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)

    print("✅ Metadata file created")

    print("\n" + "=" * 60)
    print("✅ BANGLADESH CERTIFICATE GENERATION COMPLETE")
    print("=" * 60)
    print("\n📁 Generated files:")
    print(f"  • 🇧🇩 Root CA: {CERT_DIR}/ca.crt")
    print(f"  • 🇧🇩 Server Certificate: {CERT_DIR}/server.crt")
    print(f"  • 🔑 Server Key: {CERT_DIR}/server.key")
    print(f"  • 📋 Metadata: {CERT_DIR}/metadata.json")

    print("\n📁 Directory structure:")
    print(f"  • 📂 {CERT_DIR}/clients/ - For user certificates (empty)")
    print(f"  • 📂 {CERT_DIR}/opa_agent/ - For OPA Agent RSA keys (empty)")
    print(f"  • 📂 {CERT_DIR}/services/ - For service certificates (empty)")
    print(f"  • 📂 {CERT_DIR}/user_keys/ - For user RSA keys (empty)")

    print("\n🚀 Next steps:")
    print("  1. Run this script to regenerate certificates if needed")
    print("  2. User certificates will be generated during registration")
    print("  3. OPA Agent will generate its own RSA keys on first run")

    print("\n⚠️  IMPORTANT:")
    print("  • Keep ca.key secure! Never share or commit to version control")
    print("  • User certificates will have Bangladesh context during registration")
    print("  • Certificates include: C=BD, ST=Dhaka Division, L=Dhaka")

    return True


if __name__ == "__main__":
    generate_certificates()
